name: ml_experiments
channels:
  - conda-forge
dependencies:
  - numpy
  - scikit-learn
  - scikit-posthocs
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - pandas
  - mlflow
  - postgresql
  - psycopg2
  - pytest
  - ipykernel
  - ipywidgets
  - dask
  - distributed
  - dask-jobqueue
  - tqdm
  - optuna
  - pip
  - pip:
    - -e .
    - openml
    - optuna-integration
    - func-timeout
